Add owners with all the maintainers
buildpacks/community pull request #112
Opened 2021-07-06 19:03 UTC by samj1912

2021-07-06 19:06 UTC, samj1912 commented
cc @buildpacks/core-team @buildpacks/buildpack-authors-tooling-maintainers @buildpacks/implementation-maintainers @buildpacks/distribution-maintainers @buildpacks/platform-maintainers @buildpacks/learning-maintainers to verify their email addresses.

2021-07-06 19:16 UTC, dfreilich approved these changes
It would be great if we could have some docs, maybe in GOVERNANCE, which describes the steps to add someone as a maintainer (one of which would include adding the appropriate line to this, and perhaps requesting access to cncf list), so that this list doesn't get out of date

2021-07-06 19:22 UTC, hone commented
Do we want to use vmware email addresses now?

@elbandito do you want to change to your personal email address?

2021-07-06 19:22 UTC, hone approved these changes

2021-07-06 19:46 UTC, jromero commented on OWNERS.md
> +- Javier Romero, <j.romero.1214@gmail.com> ([@jromero](https://github.com/jromero))
```suggestion
- Javier Romero, <root@jromero.codes> ([@jromero](https://github.com/jromero))
```

Can I use my cool domain name? I'm not paying the annual fees for nothing.

2021-07-06 19:47 UTC, samj1912 commented
> It would be great if we could have some docs, maybe in GOVERNANCE, which describes the steps to add someone as a maintainer (one of which would include adding the appropriate line to this, and perhaps requesting access to cncf list), so that this list doesn't get out of date

Yup, we need to consolidate the steps to add the maintainers somewhere. Currently we need this owners file so that CNCF can sync this file with service desk access and access to the buildpacks maintainers list.

> Do we want to use vmware email addresses now?

Don't know which ones to use. I copied the emails from slack.

2021-07-06 21:21 UTC, sclevine commented
@ekcasey @nebhale @natalieparellano can you suggest alternative emails in this PR?

2021-07-06 21:29 UTC, natalieparellano commented on OWNERS.md
> +- Natalie Arellano, <narellano@pivotal.io> ([@natalieparellano](https://github.com/natalieparellano))
```suggestion
- Natalie Arellano, <narellano@vmware.com> ([@natalieparellano](https://github.com/natalieparellano))
```

2021-07-07 18:56 UTC, ekcasey requested changes

2021-07-07 18:56 UTC, ekcasey commented on OWNERS.md
> +- Emily Casey, <ecasey@pivotal.io> ([@ekcasey](https://github.com/ekcasey))
```suggestion
- Emily Casey, <ecasey@vmware.com> ([@ekcasey](https://github.com/ekcasey))
```

2021-07-08 10:13 UTC, samj1912 commented
@sclevine moved to the OWNERS format similar to the one in spec.

2021-07-08 16:40 UTC, elbandito commented on OWNERS
> +Travis Longoria, Salesforce <tlongoria@heroku.com> (@elbandito)
@samj1912 could you change my email to: `longoria.public@gmail.com`
Thanks!

2021-07-09 13:13 UTC, jromero approved these changes

2021-07-09 14:05 UTC, jkutner approved these changes

2021-07-09 14:55 UTC, elbandito approved these changes

2021-07-12 18:37 UTC, hone approved these changes

2021-07-28 18:24 UTC, nebhale requested changes

2021-07-28 18:24 UTC, nebhale commented on OWNERS
> +Ben Hale, VMware <bhale@vmware.com> (@nebhale)
```suggestion
Ben Hale, VMware <nebhale@nebhale.com> (@nebhale)
```

2021-07-28 18:27 UTC, sclevine approved these changes

2021-07-28 18:28 UTC, nebhale approved these changes

2021-07-28 18:29 UTC, ekcasey approved these changes

2021-07-28 18:29 UTC, ekcasey commented on OWNERS
> +Emily Casey, VMware <ecasey@vmware.com> (@ekcasey)
```suggestion
Emily Casey, VMware <emilykimballcasey@gmail.com> (@ekcasey)
```

Sorry, changed my mind. I'd like to use my personal email.

2021-07-29 10:57 UTC, samj1912 commented
@dfreilich @natalieparellano @jabrown85 do your emails look good?

2021-07-30 05:13 UTC, dfreilich approved these changes

2021-08-10 16:27 UTC, jabrown85 approved these changes

2021-08-10 16:31 UTC, merged